<?php

namespace Macmotp\Support;

enum CurrencyFlag: string
{
    case AED = 'ae'; // United Arab Emirates Dirham - United Arab Emirate
    case AFN = 'af'; // Afghan Afghani - Afghanistan
    case ALL = 'al'; // Albanian Lek - Albania
    case AMD = 'am'; // Armenian Dram - Armenia
    case ANG = 'cw'; // Netherlands Antillean Guilder - Curaçao
    case AOA = 'ao'; // Angolan Kwanza - Angola
    case ARS = 'ar'; // Argentine Peso - Argentina
    case AUD = 'au'; // Australian Dollar - Australia
    case AWG = 'aw'; // Aruban Florin - Aruba
    case AZN = 'az'; // Azerbaijani Manat - Azerbaijan
    case BAM = 'ba'; // Bosnia and Herzegovina Convertible Mark - Bosnia and Herzegovina
    case BBD = 'bb'; // Barbados Dollar - Barbados
    case BDT = 'bd'; // Bangladeshi Taka - Bangladesh
    case BGN = 'bg'; // Bulgarian Lev - Bulgaria
    case BHD = 'bh'; // Bahraini Dinar - Bahrain
    case BIF = 'bi'; // Burundian Franc - Burundi
    case BMD = 'bm'; // Bermudian Dollar - Bermuda
    case BND = 'bn'; // Brunei Dollar - Brunei
    case BOB = 'bo'; // Bolivian Boliviano - Bolivia
    case BRL = 'br'; // Brazilian Real - Brazil
    case BSD = 'bs'; // Bahamian Dollar - Bahamas
    case BTC = '--'; // Bitcoin - No Flag
    case BTN = 'bt'; // Bhutanese Ngultrum - Bhutan
    case BWP = 'bw'; // Botswana Pula - Botswana
    case BYN = 'by'; // Belarusian Ruble - Belarus
    case BZD = 'bz'; // Belize Dollar - Belize
    case CAD = 'ca'; // Canadian Dollar - Canada
    case CDF = 'cd'; // Congolese Franc - Democratic Republic of the Congo
    case CHF = 'ch'; // Swiss Franc - Switzerland
    case CLP = 'cl'; // Chilean Peso - Chile
    case CNY = 'cn'; // Chinese Yuan - Renminbi - China
    case COP = 'co'; // Colombian Peso - Colombia
    case CRC = 'cr'; // Costa Rican Colón - Costa Rica
    case CUP = 'cu'; // Cuban Peso - Cuba
    case CVE = 'cv'; // Cape Verdean Escudo - Cape Verde
    case CZK = 'cz'; // Czech Koruna - Czechia
    case DJF = 'dj'; // Djiboutian Franc - Djibouti
    case DKK = 'dk'; // Danish Krone - Denmark
    case DOP = 'do'; // Dominican Peso - Dominican Republic
    case DZD = 'dz'; // Algerian Dinar - Algeria
    case EGP = 'eg'; // Egyptian Pound - Egypt
    case ERN = 'er'; // Eritrean Nakfa - Eritrea
    case ETB = 'et'; // Ethiopian Birr - Ethiopia
    case EUR = 'eu'; // Euro - Europe
    case FJD = 'fj'; // Fijian Dollar - Fiji
    case FKP = 'fk'; // Falkland Islands Pound - Falkland Islands
    case GBP = 'gb'; // British Pound - United Kingdom
    case GEL = 'ge'; // Georgian Lari - Georgia
    case GHS = 'gh'; // Ghanaian Cedi - Ghana
    case GIP = 'gi'; // Gibraltar Pound - Gibraltar
    case GMD = 'gm'; // Gambian Dalasi - Gambia
    case GNF = 'gn'; // Guinean Franc - Guinea
    case GTQ = 'gt'; // Guatemalan Quetzal - Guatemala
    case GYD = 'gy'; // Guyanese Dollar - Guyana
    case HKD = 'hk'; // Hong Kong Dollar - Hong Kong
    case HNL = 'hn'; // Honduran Lempira - Honduras
    case HTG = 'ht'; // Haitian Gourde - Haiti
    case HUF = 'hu'; // Hungarian Forint - Hungary
    case IDR = 'id'; // Indonesian Rupiah - Indonesia
    case ILS = 'il'; // Israeli New Shekel - Israel
    case INR = 'in'; // Indian Rupee - India
    case IQD = 'iq'; // Iraqi Dinar - Iraq
    case IRR = 'ir'; // Iranian Rial - Irani
    case ISK = 'is'; // Icelandic Króna - Iceland
    case JMD = 'jm'; // Jamaican Dollar - Jamaica
    case JOD = 'jo'; // Jordanian Dinar - Jordan
    case JPY = 'jp'; // Japanese Yen - Japan
    case KES = 'ke'; // Kenyan Shilling - Kenya
    case KGS = 'kg'; // Kyrgyz Som - Kyrgyzstan
    case KHR = 'kh'; // Cambodian Riel - Cambodia
    case KMF = 'km'; // Comorian Franc - Comoros
    case KPW = 'kp'; // North Korean Won - North Korea
    case KRW = 'kr'; // South Korean Won - South Korea
    case KWD = 'kw'; // Kuwaiti Dinar - Kuwait
    case KYD = 'ky'; // Cayman Islands Dollar - Cayman Islands
    case KZT = 'kz'; // Kazakhstani Tenge - Kazakhstan
    case LAK = 'la'; // Lao Kip - Laos
    case LBP = 'lb'; // Lebanese Pound - Lebanon
    case LKR = 'lk'; // Sri Lankan Rupee - Sri Lanka
    case LRD = 'lr'; // Liberian Dollar - Liberia
    case LSL = 'ls'; // Lesotho Loti - Lesotho
    case LYD = 'ly'; // Libyan Dinar - Libya
    case MAD = 'ma'; // Moroccan Dirham - Morocco
    case MDL = 'md'; // Moldovan Leu - Moldova
    case MGA = 'mg'; // Malagasy Ariary - Madagascar
    case MKD = 'mk'; // Macedonian Denar - North Macedonia
    case MMK = 'mm'; // Burmese Kyat - Myanmar
    case MNT = 'mn'; // Mongolian Tögrög - Mongolia
    case MOP = 'mo'; // Macanese Pataca - Macao
    case MRU = 'mr'; // Mauritanian Ouguiya - Mauritania
    case MUR = 'mu'; // Mauritian Rupee - Mauritius
    case MVR = 'mv'; // Maldivian Rufiyaa - Maldives
    case MWK = 'mw'; // Malawian Kwacha - Malawi
    case MXN = 'mx'; // Mexican Peso - Mexico
    case MYR = 'my'; // Malaysian Ringgit - Malaysia
    case MZN = 'mz'; // Mozambican Metical - Mozambique
    case NAD = 'na'; // Namibian Dollar - Namibia
    case NGN = 'ng'; // Nigerian Naira - Nigeria
    case NIO = 'ni'; // Nicaraguan Córdoba - Nicaragua
    case NOK = 'no'; // Norwegian Krone - Norway
    case NPR = 'np'; // Nepalese Rupee - Nepal
    case NZD = 'nz'; // New Zealand Dollar - New Zealand
    case OMR = 'om'; // Omani Rial - Oman
    case PAB = 'pa'; // Panamanian Balboa - Panama
    case PEN = 'pe'; // Peruvian Sol - Peru
    case PGK = 'pg'; // Papua New Guinean Kina - Papua New Guinea
    case PHP = 'ph'; // Philippine Peso - Philippines
    case PKR = 'pk'; // Pakistani Rupee - Pakistan
    case PLN = 'pl'; // Polish Złoty - Poland
    case PYG = 'py'; // Paraguayan Guaraní - Paraguay
    case QAR = 'qa'; // Qatari Riyal - Qatar
    case RON = 'ro'; // Romanian Leu - Romania
    case RSD = 'rs'; // Serbian Dinar - Serbia
    case RUB = 'ru'; // Russian Ruble - Russia
    case RWF = 'rw'; // Rwandan Franc - Rwanda
    case SAR = 'sa'; // Saudi Riyal - Saudi Arabia
    case SBD = 'sb'; // Solomon Islands Dollar - Solomon Islands
    case SCR = 'sc'; // Seychellois Rupee - Seychelles
    case SDG = 'sd'; // Sudanese Pound - Sudan
    case SEK = 'se'; // Swedish Krona - Sweden
    case SGD = 'sg'; // Singapore Dollar - Singapore
    case SHP = 'sh'; // Saint Helena Pound - Saint Helena
    case SLE = 'sl'; // Sierra Leonean Leone - Sierra Leone
    case SOS = 'so'; // Somali Shilling - Somalia
    case SRD = 'sr'; // Surinamese Dollar - Suriname
    case SSP = 'ss'; // South Sudanese Pound - South Sudan
    case STN = 'st'; // São Tomé and Príncipe Dobra - São Tomé and Príncipe
    case SYP = 'sy'; // Syrian Pound - Syria
    case SZL = 'sz'; // Swazi Lilangeni - Eswatini
    case THB = 'th'; // Thai Baht - Thailand
    case TJS = 'tj'; // Tajikistani Somoni - Tajikistan
    case TMT = 'tm'; // Turkmenistani Manat - Turkmenistan
    case TND = 'tn'; // Tunisian Dinar - Tunisia
    case TOP = 'to'; // Tongan Paʻanga - Tonga
    case TRY = 'tr'; // Turkish Lira - Turkey
    case TTD = 'tt'; // Trinidad and Tobago Dollar - Trinidad and Tobago
    case TWD = 'tw'; // New Taiwan Dollar - Taiwan
    case TZS = 'tz'; // Tanzanian Shilling - Tanzania
    case UAH = 'ua'; // Ukrainian Hryvnia - Ukraine
    case UGX = 'ug'; // Ugandan Shilling - Uganda
    case USD = 'us'; // United States Dollar - United States of America
    case UYU = 'uy'; // Uruguayan Peso - Uruguay
    case UZS = 'uz'; // Uzbekistani Sum - Uzbekistan
    case VES = 've'; // Venezuelan Sovereign Bolívar - Venezuela
    case VND = 'vn'; // Vietnamese Đồng - Viet Nam
    case VUV = 'vu'; // Vanuatu Vatu - Vanuatu
    case WST = 'ws'; // Samoan Tālā - Samoa
    case XAF = 'cf'; // Central African CFA Franc - Central African Republic
    case XCD = 'ag'; // Eastern Caribbean Dollar - Antigua and Barbuda
    case XOF = 'tg'; // West African CFA Franc - Togo
    case XPF = 'pf'; // CFP Franc - French Polynesia
    case YER = 'ye'; // Yemeni Rial - Yemen
    case ZAR = 'za'; // South African Rand - South Africa
    case ZMW = 'zm'; // Zambian Kwacha - Zambia
    case ZWG = 'zw'; // Zimbabwe Gold - Zimbabwe
}
